### ISSUE TITLE
Дозакінчити із комуналкою

### ISSUE THREAD

**Issue by okmechak** [okmechak/GreenEnergy#1]
- [x] додати графіки витрачених літрів\кіловатГодин\обєм газу і ще інші важливі на твій розсуд до ексель. Ціна одної одиниці, кількість одиниць і сумарна ціна.
 - [x] створити документ в якому буде опис з посиланнями як виглядають оплати(тобто основне як формується ціна за ті послуги) за комунальні послуги(офіційні сайти) взагалі як це працює на законодавчому рівні(якось воно мабуть регулюється законом і тд). Також ті тарифи мабуть залежать від областей, від розміру домогосподарств і чи це є підприємництво чи ні.
 
 https://docs.google.com/spreadsheets/d/17gA_G0fUTUdgq0S-1YR5zlTv8PT7t4ztJmcHIVcXOow/edit?usp=sharing

**Comment by okmechak** [comment]
4 години

**Comment by Travique** [comment]
https://docs.google.com/document/d/1jKW6ISnk4O1tMw0JE1ils3C8hPWDdEpSY3opD7-MxqI/edit
Тут можна почитати за газ, знайшов трохи інформації про ПДВ та його обрахування.

**Comment by Travique** [comment]
![image](https://user-images.githubusercontent.com/46631319/115113777-9f35a000-9f94-11eb-85a1-97fff4b7274a.png)

**Comment by Travique** [comment]
https://lv.gaszbut.com.ua/ua/electricity/id/informacija-dlja-spozhivachiv-elektroenergiji-38824

**Comment by Travique** [comment]
https://iotji.io/solutions/dlya-rozumnoho-budynku/

**Comment by Travique** [comment]
З водовідведенням і водопостачанням так  не вийде з однієї причини, на Сокальському сайті Водоканалу немає взагалі по цьому інфи: 

![image](https://user-images.githubusercontent.com/46631319/115114592-d73ee200-9f98-11eb-9810-328570f32a7d.png)

Це смішно :D.

**Comment by okmechak** [comment]
Ще точно не знаю, але швидше за вс е ми група "B"
https://www.yug-ie.com/zapytannya-vidpovid/:
```
За якими критеріями клієнти розподіляються на групи відносно організації обліку (група «А»/ група «Б»)?
Споживачі групи «А» – це споживачі, площадки вимірювання яких забезпечені прийнятою до розрахунків за електричну енергію схемою обліку електричної енергії енергії (де вимірюється надходження електричної енергії на площадку) із встановленими та введеними в експлуатацію ЛУЗОД, АСКОЕ, АСЗД або лічильниками диференційного (погодинного, зонного) обліку електричної енергії із гарантованим щодобовим зчитуванням показів, належать до групи “А” за умови забезпечення визначеним споживачем, Оператором АСКОЕ або ППКО щодобового зчитування, формування та передачі сформованих погодинних даних комерційного обліку до ОСР/НЕК.

Споживачі групи «Б» – це споживачі, площадки вимірювання яких, не відповідають вимогам щодо організації обліку електроенергії для групи «а».


Процедура віднесення площадок вимірювання споживачів до групи “А” врегульована додатком до Тимчасового порядку визначення обсягів купівлі електричної енергії на ринку електричної енергії електропостачальниками та операторами систем розподілу на перехідний період, затвердженого постановою НКРЕКП від 28 грудня 2018 року N 2118.

За якими принципами проводяться нарахування за електроенергію для споживачів групи «А»/групи «Б»?
Для споживачів групи «А», що є споживачами за вільними цінами, погодинна ціна буде розраховуватися на основі фактичного графіка погодинного електроспоживання цих клієнтів та погодинних цін закупівлі електроенергії на ринку.

Для споживачів групи «Б» ціна буде розраховуватися з урахуванням графіку погодинного споживання усіх клієнтів групи «Б» постачальника в цілому та погодинної вартості на ринку.
```

**Comment by Travique** [comment]
Добре, працюю над цим


вт, 20 квіт. 2021, 01:23 користувач Oleg ***@***.***> пише:
