### ISSUE TITLE
Планування в MAYA і розміри.

### ISSUE THREAD

**Issue by Travique** [okmechak/GreenEnergy#10]
Зробити референси і розмітку модельки. По бажанню добавити текстури.

**Comment by okmechak** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/5883082/116437543-d5550880-a84d-11eb-8d18-afae1fda1571.jpg)

**Comment by Travique** [comment]
https://docs.google.com/document/d/145W4Q6NBoFsFcZvGKdpdYO1WOvDAcXbS5AdwGINdCK0/edit
