### ISSUE TITLE
Зробити скани плану хати

### ISSUE THREAD

**Issue by okmechak** [okmechak/GreenEnergy#3]
Вислати їх @Travique  для моделювання 3D

**Comment by okmechak** [comment]
на четвер

**Comment by okmechak** [comment]
@Travique  із цим прийдеться зачекати до 27го числа :c

**Comment by okmechak** [comment]
Наразі вирішили що робимо @Travique  план хати

**Comment by Travique** [comment]
Плани хати є, тому перехід до виконання ---> Моделювання. 

Виконано.

**Comment by okmechak** [comment]
![PXL_20210429_161648957~3](https://user-images.githubusercontent.com/5883082/116591173-d2761880-a91e-11eb-9645-94738e45f55b.jpg)
![PXL_20210429_161611812](https://user-images.githubusercontent.com/5883082/116591178-d30eaf00-a91e-11eb-964a-7a9b35b3992c.jpg)

**Comment by okmechak** [comment]
@Travique  скани є. Колсиь думаю скористаємося, наразі таску закриваю
