### ISSUE TITLE
3D модель дому

### ISSUE THREAD

**Issue by okmechak** [okmechak/GreenEnergy#5]
3D модель дому потрібна, щоб потім створити термічну модель дому.. в першому наближенні найважливішими параметрами є: площі поверхонь(стіни, вікна, підлога, стеля), товщина стін і об'єми кімнат.

**Comment by okmechak** [comment]
оцінюємо 2 години

**Comment by Travique** [comment]
В процесі. Це виявилось важче, ніж я думав. Оскільки треба дотримуватись кожного мм. в обробці.

**Comment by Travique** [comment]
Окрім модельки я тобі надам параметри :)

![image](https://user-images.githubusercontent.com/46631319/115144781-39f6b300-a057-11eb-96a2-a70551d7dd29.png)

**Comment by Travique** [comment]
єслі шо, 1, розмір 1:10... чи 10 до 1. В любому випадку, моделька в 10 раз більша за справжнє.

**Comment by Travique** [comment]
5.5 годин до цього моменту: 
![image](https://user-images.githubusercontent.com/46631319/115160318-4f43ff80-a0a0-11eb-9ae5-9187b4706dc3.png)

**Comment by okmechak** [comment]
>я довго зрівнював розміри хати з рулетки, а також з планом хати

і що схордяться розміри з планом?))

Картинка наче я в тебе під будинком стою.. все знайоме :)

**Comment by Travique** [comment]
Розміри 10:1. Максимально точні, але я працюю над проектами в силах
можливостей


вт, 20 квіт. 2021, 01:09 користувач Oleg ***@***.***> пише:

**Comment by Travique** [comment]
Я кину пару файлів

**Comment by okmechak** [comment]
Ті розміри як вони є на картинці(ця точність) - це більш ніж достатньо

вт, 20 квіт. 2021 о 00:26 Bohdan Barannik ***@***.***> пише:

**Comment by Travique** [comment]
Зроблю кришу завтра, осталась корма, бо в нас там горище є, оказалось)

вт, 20 квіт. 2021, 01:28 користувач Oleg ***@***.***> пише:

**Comment by Travique** [comment]
![image](https://user-images.githubusercontent.com/46631319/115311825-f7c59280-a178-11eb-9168-31fa1db638f1.png)

@okmechak

**Comment by okmechak** [comment]
![signal-2021-04-18-142402](https://user-images.githubusercontent.com/5883082/115864777-a696f680-a437-11eb-8b3b-175ede271348.jpeg)

**Comment by okmechak** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/5883082/115864861-ce865a00-a437-11eb-8273-167f9bf4f776.jpg)
